version: '3'

services:
  php-cli:
    build:
      context: ./php-cli
      dockerfile: Dockerfile
    container_name: reminder-tg-bot_php-cli
    volumes:
      - ./code:/code/
    tty: true
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # REDIS_PASSWORD:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # Порт для приложений (AMQP)
      - "15672:15672"    # Порт для веб-интерфейса управления
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local
